#!/usr/bin/env python
# Copyright 2009 by Ka-Ping Yee <ping@zesty.ca>
#
# multitet is free software: you can redistribute and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation (either version 3, or, at your option, any later version).
#
# multitet is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for details.
# You should have received a copy of the GNU General Public License along
# with multitet.  If not, see <http://www.gnu.org/licenses/>.

import sys

try:
    import multitetris
except ImportError:
    sys.path = ['..', '/usr/share/games'] + sys.path

    try:
        import multitetris
    except ImportError:
        sys.stderr.write('ERROR: Cannot find multitetris package: reinstall the game.\n')
        sys.exit(1)

if __name__ == '__main__':
    multitetris.Multitet.start()
